### ISSUE TITLE
Nix!

### ISSUE THREAD

**Issue by oszilloskop** [oszilloskop/ffm-freifunk-faltblatt-6-seiten#1]
Bilder

**Comment by oszilloskop** [comment]
Datenablage für README.md
![1](https://user-images.githubusercontent.com/1434390/39678066-11261060-5186-11e8-9e85-1169e9b96233.png)
![2](https://user-images.githubusercontent.com/1434390/39678068-1a8ff710-5186-11e8-99e2-e73165737518.png)

**Comment by oszilloskop** [comment]
![ff_faltblatt_6_seiten_9 8x9 8-seite001](https://user-images.githubusercontent.com/1434390/44003785-f1d313dc-9e58-11e8-9124-2b032f4c5967.png)

![ff_faltblatt_6_seiten_9 8x9 8-seite002](https://user-images.githubusercontent.com/1434390/44003691-2f48e496-9e57-11e8-89df-2e1592b07597.png)

**Comment by rubo77** [comment]
1.
im Text ist du, dich, dein,... manchmal gross manchmal klein:

- Dafür brauchst **Du** einen passenden...
- Finde einen Hotspot in **deiner** nähe...



 Dies muss einheitlich immer gross oder immer klein.


2.
Ein einstiegsrouter gibts schon ab 30€

**Comment by oszilloskop** [comment]
Ich bin alte Schule. 
Daher sehen meine Texte **immer** so aus:

1) Persönliche Anrede immer groß.
Beispiel: 
Dafür brauchst **Du** einen ...

2) Possessivpronomen immer klein.
Beispiel: 
Finde einen Hotspot in **deiner** Nähe ....

**Comment by rubo77** [comment]
Das ist glaube ich grammatikalisch falsch, oder?

Ich würde alles klein schreiben, dann kann sich keiner dran stoßen.
