### ISSUE TITLE
Konfiguration in Datei auslagern

### ISSUE THREAD

**Issue by MyIgel** [oszilloskop/ffm-freifunk-faltblatt-6-seiten#3]
Heute abend mache ich einen Pull dazu

**Comment by oszilloskop** [comment]
Vielen Danke für die Anpassungen und die Korrekturen.
Leider bin ich mit der GUI von GitHub noch nicht wirklich vertraut. Werde aber mal versuchen den Pull-Request zu übernehmen.
Bitte gestatte mir einige (kleine) Anpassungen rückgängig zu machen.

Auch hier ist es möglich, dass PHP-Laien wie ich unterwegs sind (das ist mein erstes PHP-Skript).
Daher möchte ich die config.php für Unwissende doch etwas übersichtlicher machen. 

So jetzt habe ich keine Ahnung wo ich hier was machen muss.....aber das wird schon.....

**Comment by MyIgel** [comment]
Der PR hat ja anscheinend geklappt ;)
Stimmt, ich hätte meine Änderungen noch kommentieren sollen, war aber um die Uhrzeit nicht mehr drinnen ^^

Grundsätzlich ist es aber sinnvoll, den Programmcode & die zu verarbeitenden Daten (in Ordnern) getrennt zu verwalten. Dadurch wird alles übersichtlicher und einfacher zu warten.
Der Vorteil des out-Ordners ist, dass die generierten Dateien nicht zwischen den Projektdaten rumfliegen (-> übersichtlicher).
Außerdem lässt sich so die Konfiguration in der .gitignore vereinfachen um vernünftig ein `git add *` ausführen zu können

**Comment by oszilloskop** [comment]
Generell gebe ich Dir recht mit der Trennung von Code und Daten/Output.

Hauptgrund für das GitHub-Archiv war eigentlich nur das Bereitstellen des Scribus-Flyer-Projekts und des Exports daraus. Der Export liegt jetzt ja schon im Wurzelverzeichnis. 

Das PHP-Skript war/ist eigentlich nur als kleines Add-On angedacht. Solange das Skript keine Webanwendung wird (ich plane es jedenfalls nicht), so wird es wohl max. ein/zwei mal von dem (Laien) Anwender benutz werden. Daher möchte ich es lieber gerne vom Hauptprojekt getrennt sehen.

Für Frankfurt und Duckburg wird das PHP-Skript nicht wirklich benötigt. Da ist schon alles im Scribus-Projekt enthalten. Duckburg musste auch nur als Muster herhalten. Damit habe ich die Position/Deckungsgleichheit vom Scribus-Duckburg-Original und der Skript-Ausgabe überprüft. 

Aber trotzdem vielen Dank für deine Mühe. Habe dadurch einiges über PHP gelernt.
Evtl. lasse ich mich ja doch noch überzeugen....

Habe gesehen, dass Du aus K. bist. 
Falls Du Interesse an Frankfurter Flyern hast, ich habe gerade welche in Auftrag gegeben. Da kann ich Dir gerne welche abtreten. Ich denke mal Du hast den GitHub Link aus der FF-FFM Mailingliste, dann hast Du auch meine Emailadresse.
